-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Imp.

module AbsImp where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Prog = Prog [Def]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Def
    = DataType Id Tps [Decl] | Method Id Tps [Param] Param [Stat]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Tps = TypeParEty | TypeParSeq [Id]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl = Decl Id Types
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Types = TypesEty | TypesSeq [Type]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type = Type Id Types | TypeVar Id
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Param = Param Id Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stat
    = StmBlock [Stat]
    | StmVarDecl [Param]
    | StmAssignEty
    | StmAssignNEty [Id] [Exp]
    | StmCase Id [Branch]
    | StmWhile Id [Branch]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Branch = Branch Left [Stat]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Left = LeftConstrEty Id | LeftConstr Id [Id]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp = ExpVar Id | ExpConstr Id [Exp] | ExpCall Id [Exp]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Id = Id String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

