-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintImp.

module PrintImp where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsImp

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsImp.Id where
  prt _ (AbsImp.Id i) = doc $ showString i
instance Print AbsImp.Prog where
  prt i = \case
    AbsImp.Prog defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print [AbsImp.Def] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsImp.Def where
  prt i = \case
    AbsImp.DataType id_ tps decls -> prPrec i 0 (concatD [doc (showString "data"), prt 0 id_, prt 0 tps, doc (showString "="), prt 0 decls])
    AbsImp.Method id_ tps params param stats -> prPrec i 0 (concatD [doc (showString "method"), prt 0 id_, prt 0 tps, doc (showString "("), prt 0 params, doc (showString ")"), doc (showString "returns"), doc (showString "("), prt 0 param, doc (showString ")"), doc (showString "{"), prt 0 stats, doc (showString "}")])

instance Print [AbsImp.Decl] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print [AbsImp.Stat] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsImp.Param] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsImp.Tps where
  prt i = \case
    AbsImp.TypeParEty -> prPrec i 0 (concatD [])
    AbsImp.TypeParSeq ids -> prPrec i 0 (concatD [doc (showString "<"), prt 0 ids, doc (showString ">")])

instance Print [AbsImp.Id] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsImp.Decl where
  prt i = \case
    AbsImp.Decl id_ types -> prPrec i 0 (concatD [prt 0 id_, prt 0 types])

instance Print AbsImp.Types where
  prt i = \case
    AbsImp.TypesEty -> prPrec i 0 (concatD [])
    AbsImp.TypesSeq types -> prPrec i 0 (concatD [doc (showString "<"), prt 0 types, doc (showString ">")])

instance Print [AbsImp.Type] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsImp.Type where
  prt i = \case
    AbsImp.Type id_ types -> prPrec i 0 (concatD [prt 0 id_, prt 0 types])
    AbsImp.TypeVar id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print AbsImp.Param where
  prt i = \case
    AbsImp.Param id_ type_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 type_])

instance Print AbsImp.Stat where
  prt i = \case
    AbsImp.StmBlock stats -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stats, doc (showString "}")])
    AbsImp.StmVarDecl params -> prPrec i 0 (concatD [doc (showString "var"), prt 0 params])
    AbsImp.StmAssignEty -> prPrec i 0 (concatD [doc (showString ":=")])
    AbsImp.StmAssignNEty ids exps -> prPrec i 0 (concatD [prt 0 ids, doc (showString ":="), prt 0 exps])
    AbsImp.StmCase id_ branchs -> prPrec i 0 (concatD [doc (showString "case"), prt 0 id_, doc (showString "of"), doc (showString "{"), prt 0 branchs, doc (showString "}")])
    AbsImp.StmWhile id_ branchs -> prPrec i 0 (concatD [doc (showString "while"), prt 0 id_, doc (showString "is"), doc (showString "{"), prt 0 branchs, doc (showString "}")])

instance Print [AbsImp.Branch] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [AbsImp.Exp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsImp.Branch where
  prt i = \case
    AbsImp.Branch left stats -> prPrec i 0 (concatD [prt 0 left, doc (showString "->"), prt 0 stats])

instance Print AbsImp.Left where
  prt i = \case
    AbsImp.LeftConstrEty id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsImp.LeftConstr id_ ids -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 ids, doc (showString "]")])

instance Print AbsImp.Exp where
  prt i = \case
    AbsImp.ExpVar id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsImp.ExpConstr id_ exps -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 exps, doc (showString "]")])
    AbsImp.ExpCall id_ exps -> prPrec i 0 (concatD [prt 0 id_, doc (showString "("), prt 0 exps, doc (showString ")")])
