-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelImp where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsImp

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transId :: AbsImp.Id -> Result
transId x = case x of
  AbsImp.Id string -> failure x

transProg :: AbsImp.Prog -> Result
transProg x = case x of
  AbsImp.Prog defs -> failure x

transDef :: AbsImp.Def -> Result
transDef x = case x of
  AbsImp.DataType id tps decls -> failure x
  AbsImp.Method id tps params param stats -> failure x

transTps :: AbsImp.Tps -> Result
transTps x = case x of
  AbsImp.TypeParEty -> failure x
  AbsImp.TypeParSeq ids -> failure x

transDecl :: AbsImp.Decl -> Result
transDecl x = case x of
  AbsImp.Decl id types -> failure x

transTypes :: AbsImp.Types -> Result
transTypes x = case x of
  AbsImp.TypesEty -> failure x
  AbsImp.TypesSeq types -> failure x

transType :: AbsImp.Type -> Result
transType x = case x of
  AbsImp.Type id types -> failure x
  AbsImp.TypeVar id -> failure x

transParam :: AbsImp.Param -> Result
transParam x = case x of
  AbsImp.Param id type_ -> failure x

transStat :: AbsImp.Stat -> Result
transStat x = case x of
  AbsImp.StmBlock stats -> failure x
  AbsImp.StmVarDecl params -> failure x
  AbsImp.StmAssignEty -> failure x
  AbsImp.StmAssignNEty ids exps -> failure x
  AbsImp.StmCase id branchs -> failure x
  AbsImp.StmWhile id branchs -> failure x

transBranch :: AbsImp.Branch -> Result
transBranch x = case x of
  AbsImp.Branch left stats -> failure x

transLeft :: AbsImp.Left -> Result
transLeft x = case x of
  AbsImp.LeftConstrEty id -> failure x
  AbsImp.LeftConstr id ids -> failure x

transExp :: AbsImp.Exp -> Result
transExp x = case x of
  AbsImp.ExpVar id -> failure x
  AbsImp.ExpConstr id exps -> failure x
  AbsImp.ExpCall id exps -> failure x
