-- File generated by the BNF Converter (bnfc 2.9.6.3).

-- | The abstract syntax of language Lista.

module AbsLista where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data L = LNum Integer | LNumList Integer L
  deriving (C.Eq, C.Ord, C.Show, C.Read)

