-- File generated by the BNF Converter (bnfc 2.9.6.3).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module SkelLista where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLista

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transL :: AbsLista.L -> Result
transL x = case x of
  AbsLista.LNum integer -> failure x
  AbsLista.LNumList integer l -> failure x
