void foo0();
void foo0(int);
void foo0(int, bool);
void foo0(int, d);
void foo0(int, d);
void foo0(int, d, q);
void foo0(int x, d, q);
void foo0(int x, d y, q);
void foo0(int x, d y, q z);
void foo0(int, d y, q);
void foo0(int, d y, q z);
void foo0(int x, d, q z);
void foo0(int x, d, q z = "apa");
void foo0(int x, d y = t, q z = t1);
void foo1();
int foo1(int);
void foo1(int, const bool);
void foo1(int, const d &);
void foo1(int, d);
void foo1(int, const d, q &);
void foo1(int x, d &, q);
void foo1(int x, const d & y, q);
void foo1(int x, d y, q z);
void foo1(const int, d y, q);
void foo1(int, d & y, q & z);
void foo1(int x, d, q z);
void foo1(int x, d, const q z = "apa");
int foo1(int x, d & y = t, const q & z = t1);
